package com.acme.moviebot.bot.internal.admin;

public enum AdminSessionState {
    IDLE,
    WAITING_MOVIE_NAME,
    WAITING_MOVIE_SEARCH,
    WAITING_MOVIE_ORIGINAL_NAME,
    WAITING_MOVIE_DESCRIPTION,
    WAITING_SEASON_NUMBER,
    WAITING_SEASON_NAME,
    WAITING_EPISODE_NUMBER,
    WAITING_EPISODE_NAME,
    WAITING_EPISODE_DESCRIPTION,
    WAITING_EPISODE_VIDEO,
    CONFIRMING_PUBLISH
}
