package com.acme.moviebot.bot.internal.admin;

public enum AdminSessionState {
    IDLE,
    WAITING_MOVIE_NAME,
    WAITING_MOVIE_SEARCH,
    WAITING_MOVIE_CHINESE_NAME,
    WAITING_MOVIE_DESCRIPTION,
    WAITING_MOVIE_FULL,
    WAITING_MOVIE_THUMBNAIL,
    WAITING_MOVIE_DETAILS_UPDATE,
    WAITING_MOVIE_THUMBNAIL_UPDATE,
    WAITING_SEASON_NUMBER,
    WAITING_SEASON_EPISODE_COUNT,
    WAITING_EPISODE_VIDEO,
    CONFIRMING_PUBLISH
}
